# Site settings
title: Chris Infante
description: Cyber Security and Cypherpunk Enthusiast
url: "https://chris-iio.github.io"
baseurl: ""

# Author
author:
  name: Chris
  bio: "Cyber Security and Cypherpunk Enthusiast"

# Social
social:
  linkedin: chr1sinfante
  github: chris-iio
  twitter: chr1sinfante

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - node_modules/
