# Site settings
title: cji-iio
description: Cyber Security and Cypherpunk Enthusiast
url: "https://chris-iio.github.io"
baseurl: ""

# Author information
author:
  name: Chris
  bio: "Cyber Security and Cypherpunk Enthusiast"

# Social media links
social:
  linkedin: chr1sinfante

# Certifications
certifications:
  - name: "SAL1"
    year: "2024"
  - name: "Security+"
    year: "2023"
  - name: "CySA+"
    year: "2023"

# Skills
skills:
  - Python
  - Linux
  - AWS
  - Splunk
  - Wireshark
  - Burp Suite

# Minima theme settings
minima:
  skin: dark # Options: auto, classic, dark, solarized
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/chr1sinfante" }

# SEO and metadata
lang: en-US
timezone: America/New_York # Update to your timezone

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - node_modules/
